# This is a basic workflow to help you get started with Actions

name: Blob storage website CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # 「AZURE_CREDENTIALS」をSettingsのSecretsに追加するのを忘れない
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob sync --account-name allrighttooursstorage -c '$web/zipcode_jp' -s .
            
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
